// DATA FOR ARTICLES
const data = [
  {
    newMarker: './img/new_icon.png',
    topOfDay: false,
    interesting: false,
    img: './img/article_image-1.png',
    date: 'Feb 23',
    time: '8 min read',
    title: 'Tips & Tricks For Cutting',
    text: 'Pruning, like any other skill, requires knowing what you are doing to achieve success. The old idea that anyone with a chain saw or a pruning saw can be a...',
  },
  {
    newMarker: '',
    topOfDay: true,
    interesting: false,
    img: './img/article_image-2.png',
    date: 'Feb 23',
    time: '8 min read',
    title: 'Professional Repot',
    text: 'Repotting a plant can seem like a difficult task because a lot of things can go wrong – you can damage...',
  },
  {
    newMarker: '',
    topOfDay: true,
    interesting: false,
    img: './img/article_image-3.png',
    date: 'Feb 23',
    time: '8 min read',
    title: 'Professional Repot',
    text: 'Pruning, like any other skill, requires knowing what you are doing to achieve success. The old idea that anyone with a chain saw or a pruning saw can be a...',
  },
  {
    newMarker: '',
    topOfDay: false,
    interesting: true,
    img: './img/article_image-4.png',
    date: 'Feb 23',
    time: '8 min read',
    title: 'Watering mastery',
    text: 'Pruning, like any other skill, requires knowing what you are doing to achieve success. The old idea that anyone with a chain saw or a pruning saw can be a...',
  },
  {
    newMarker: '',
    topOfDay: false,
    interesting: true,
    img: './img/article_image-4.png',
    date: 'Feb 23',
    time: '8 min read',
    title: 'Plant pot secrets',
    text: 'Pruning, like any other skill, requires knowing what you are doing to achieve success. The old idea that anyone with a chain saw or a pruning saw can be a...',
  },
  {
    newMarker: '',
    topOfDay: false,
    interesting: true,
    img: './img/article_image-5.png',
    date: 'Feb 23',
    time: '8 min read',
    title: 'Professional Repot',
    text: 'Pruning, like any other skill, requires knowing what you are doing to achieve success. The old idea that anyone with a chain saw or a pruning saw can be a...',
  },
  {
    newMarker: '',
    topOfDay: false,
    interesting: true,
    img: './img/article_image-6.png',
    date: 'Feb 23',
    time: '8 min read',
    title: 'Watering mastery',
    text: 'Pruning, like any other skill, requires knowing what you are doing to achieve success. The old idea that anyone with a chain saw or a pruning saw can be a...',
  },
  {
    newMarker: '',
    topOfDay: false,
    interesting: true,
    img: './img/article_image-4.png',
    date: 'Feb 23',
    time: '8 min read',
    title: 'Professional Repot',
    text: 'Pruning, like any other skill, requires knowing what you are doing to achieve success. The old idea that anyone with a chain saw or a pruning saw can be a...',
  },
  {
    newMarker: '',
    topOfDay: false,
    interesting: true,
    img: './img/article_image-5.png',
    date: 'Feb 23',
    time: '8 min read',
    title: 'Plant pot secrets',
    text: 'Pruning, like any other skill, requires knowing what you are doing to achieve success. The old idea that anyone with a chain saw or a pruning saw can be a...',
  },
  {
    newMarker: '',
    topOfDay: false,
    interesting: true,
    img: './img/article_image-6.png',
    date: 'Feb 23',
    time: '8 min read',
    title: 'Watering mastery',
    text: 'Pruning, like any other skill, requires knowing what you are doing to achieve success. The old idea that anyone with a chain saw or a pruning saw can be a...',
  },
  {
    newMarker: '',
    topOfDay: false,
    interesting: true,
    img: './img/article_image-4.png',
    date: 'Feb 23',
    time: '8 min read',
    title: 'Watering mastery',
    text: 'Pruning, like any other skill, requires knowing what you are doing to achieve success. The old idea that anyone with a chain saw or a pruning saw can be a...',
  },
  {
    newMarker: '',
    topOfDay: false,
    interesting: true,
    img: './img/article_image-5.png',
    date: 'Feb 23',
    time: '8 min read',
    title: 'Watering mastery',
    text: 'Pruning, like any other skill, requires knowing what you are doing to achieve success. The old idea that anyone with a chain saw or a pruning saw can be a...',
  },
  {
    newMarker: '',
    topOfDay: false,
    interesting: true,
    img: './img/article_image-6.png',
    date: 'Feb 23',
    time: '8 min read',
    title: 'Watering mastery',
    text: 'test, like any other skill, requires knowing what you are doing to achieve success. The old idea that anyone with a chain saw or a pruning saw can be a...',
  },
  {
    newMarker: '',
    topOfDay: false,
    interesting: true,
    img: './img/article_image-4.png',
    date: 'Feb 23',
    time: '8 min read',
    title: 'Watering mastery',
    text: 'Svatukha Pruning, like any other skill, requires knowing what you are doing to achieve success. The old idea that anyone with a chain saw or a pruning saw can be a...',
  },
  {
    newMarker: '',
    topOfDay: false,
    interesting: true,
    img: './img/article_image-5.png',
    date: 'Feb 23',
    time: '8 min read',
    title: `Svatukha's Olha test`,
    text: 'Pruning, like any other skill, requires knowing what you are doing to achieve success. The old idea that anyone with a chain saw or a pruning saw can be a...',
  },

];

export default data;
